---
title: "p8105_hw2_NL2655"
author: "Nankun"
date: "2019/10/4"
output: github_document
---

# Library

```{r}
library(tidyverse)
library(readxl)
```

# Problem 1

## improting data

```{r}
Trash_data = 
  read_excel ("./Data/Trash-Wheel-Collection-Totals-8-6-19.xlsx", sheet="Mr. Trash Wheel", range = cell_cols("A:N")) %>% 
  janitor::clean_names() %>% 
  drop_na(dumpster) %>% 
mutate(
  sports_balls = as.integer(sports_balls))
Trash_data
```

```{r}
Pa_2017 =
read_excel("Data/Trash-Wheel-Collection-Totals-8-6-19.xlsx",sheet = "2017 Precipitation", range = "A2:B15")%>% 
  janitor::clean_names() %>% 
  drop_na(month) %>% 
  mutate(
    year = 2017
  )
Pa_2018 =
  read_excel("Data/Trash-Wheel-Collection-Totals-8-6-19.xlsx",sheet = "2018 Precipitation", range = "A2:B15") %>% 
  janitor::clean_names() %>% 
  drop_na(month) %>% 
  mutate(
    year = 2018
  )
Pa_17_18 = 
  full_join(Pa_2017, Pa_2018, by = "month") %>% 
  mutate(month = month.name)
Pa_17_18
```

# problem 2
## clean pols_month
```{r}
pols_month = 
  read_csv("Data/fivethirtyeight_datasets/pols-month.csv") %>% 
  janitor::clean_names() %>% 
  separate(mon, c("year", "month", "day"))%>% 
  mutate(
    month = as.numeric(month),
    month = month.name[month],
  ) %>% 
  pivot_longer(c(prez_gop,prez_dem),
    names_to = "president",
    names_prefix = "prez_"
  ) %>% 
  select(-day)
pols_month
```

## clean snp

```{r}
snp =
  read_csv("Data/fivethirtyeight_datasets/snp.csv") %>% 
janitor::clean_names() %>% 
  separate(date, c("month", "day", "year"))%>% 
  select(-day) %>% 
  arrange(year, as.integer(month)) %>% 
    mutate(
    month = as.numeric(month),
    month = month.name[month],
  )
snp
```

## clean unemployment
```{r}
unemployment = 
  read_csv("Data/fivethirtyeight_datasets/unemployment.csv") %>% 
  janitor::clean_names() %>% 
  pivot_longer(jan:dec,
    names_to = "month"
  ) %>% 
  mutate( 
    year = as.character(year),
    month = recode(month,
    "jan" = "January",
    "feb" = "February",
    "mar" = "March",
    "apr" = "April",
    "may" = "May",
    "jun" = "June",
    "jul" = "July",
    "aug" = "August",
    "sep" = "September",
    "oct" = "October",
    "nov" = "November",
    "dec" = "December"
  ))
unemployment
```

## merge
```{r}
snp_pol = 
  full_join(pols_month, snp, by =c("year", "month"))

Summary_data = 
  full_join(snp_pol, unemployment, by =c("year", "month"))
Summary_data
```

# Problem 3
## data cleaning
```{r}
Popular_Baby = read_csv("Data/Popular_Baby_Names.csv") %>% 
  janitor::clean_names() %>% 
  mutate_all(toupper) %>% 
  mutate(
    ethnicity = replace(ethnicity, ethnicity == "ASIAN AND PACI", "ASIAN AND PACIFIC ISLANDER"),
    ethnicity = replace(ethnicity, ethnicity == "BLACK NON HISP", "BLACK NON HISPANIC"),
    ethnicity = replace(ethnicity, ethnicity == "WHITE NON HISP", "WHITE NON HISPANIC")
  ) %>% 
  distinct()
Popular_Baby %>% 
  count(ethnicity)
Popular_Baby
```

## Table 1 "Olivia"
```{r}
Olivia_df = 
Popular_Baby %>% 
  filter(gender == "FEMALE", childs_first_name == "OLIVIA") %>% 
  select(year_of_birth, ethnicity, rank) %>% 
  arrange(year_of_birth) %>% 
  pivot_wider(
    names_from = "year_of_birth",
    values_from = "rank"
  ) %>% 
  knitr::kable()
Olivia_df
```

## Table 2 Most popular boies' names
```{r}
boy_df =
  Popular_Baby %>% 
  filter(gender == "MALE", rank == "1") %>% 
  select(year_of_birth, childs_first_name, ethnicity) %>% 
  arrange(year_of_birth) %>% 
  pivot_wider(
    names_from = "year_of_birth",
    values_from = "childs_first_name"
  ) %>% 
  knitr::kable()
boy_df
```

## Scatter plot 
```{r}
white_boy =
  Popular_Baby %>% 
  filter(gender == "MALE", ethnicity == "WHITE NON HISPANIC", year_of_birth == "2016") %>% 
  mutate(
    Name_rank = as.numeric(rank),
    Number_of_name = as.numeric(count)
  ) %>% 
  ggplot(aes(x = Name_rank, y = Number_of_name))+
  geom_point(color = "red")
white_boy
```

